<<<<<<< HEAD
spring:
  application:
    name: ChronoGarden
  datasource:
    url: jdbc:mysql://localhost:3306/chronogarden?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
  jpa:
    hibernate:
      # spring.jpa.hibernate.ddl-auto 属性来实现自动建表
      ddl-auto: update
      # spring.jpa.hibernate.show-sql 属性启用 SQL 语句的日志记录
    show-sql: true
jwt:
  secret: "buynonsense_super_secret_key_that_is_at_least_32_bytes_long_for_security"
  expiration: 86400000  # 设置为1天（单位为毫秒）
=======
spring:
  application:
    name: ChronoGarden
  datasource:
    url: jdbc:mysql://localhost:3306/chronogarden?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
  jpa:
    hibernate:
      # spring.jpa.hibernate.ddl-auto 属性来实现自动建表
      ddl-auto: update
      # spring.jpa.hibernate.show-sql 属性启用 SQL 语句的日志记录
    show-sql: true
jwt:
  secret: "buynonsense's_secret"
  expiration: 86400000  # 设置为1天（单位为毫秒）
>>>>>>> d6310dba1852a4c6218eb5bb8b4334ffdb244361
